FROM python:3.11-slim

WORKDIR /app

# Install bot dependencies from root
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy bot code and shared files
COPY bot /app/bot
COPY .env /app/.env

# Create empty bot.log if not exists
RUN touch /app/bot.log

EXPOSE 8080

CMD ["python", "-m", "bot.main"]
